name: build
on: 
  pull_request:
    types: [opened,edited,synchronize,reopened]
  push: 
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - run: yarn build